<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
/** @var $this Adyen_Payment_Block_Form_Oneclick */
?>
<?php $_code = $this->getMethodCode() ?>
<?php $originKey = $this->getOriginKey(); ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <?php
        $recurringDetails = $this->getRecurringDetails();
        if (isset($recurringDetails["variant"])):
        ?>

        <?php if (isset($recurringDetails["card_number"]) && isset($recurringDetails["card_expiryMonth"]) && isset($recurringDetails["card_expiryYear"])): ?>
        <div class="columns three a">
            <label><?php echo $this->__('Credit Card Number') ?></label>
            <span>****</span> <?php echo $recurringDetails["card_number"]; ?>
        </div>

        <div class="columns three b">
            <label><?php echo $this->__('Expiration Date') ?></label>

            <div id="static-card-expiry-<?php echo $_code; ?>" class="static-card-expiry">
                <?php echo $recurringDetails["card_expiryMonth"] . " /" . $recurringDetails["card_expiryYear"]; ?>
            </div>
        </div>

        <?php if ($this->hasInstallments()): ?>
            <div id="adyen_oneclick_installment_<?php echo $_code; ?>" class="adyen-oneclick-installments">
                <label for="<?php echo $_code ?>_installment_<?php echo $_code; ?>"
                       class="required"><em>*</em><?php echo $this->__('Installments') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_installment" name="payment[installment]"
                                class="adyen-installment number required-entry">
                            <?php foreach ($this->getInstallments() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
        <?php endif; ?>

            <?php elseif ($recurringDetails["variant"] == "elv"): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Account holder name') ?></label>
                    <span><?php echo $recurringDetails["elv_accountHolderName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('Account Number') ?></label>
                    <span><?php echo $recurringDetails["elv_bankAccountNumber"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Bank Name') ?></label>
                    <span><?php echo $recurringDetails["elv_bankName"]; ?></span>
                </div>
            <?php elseif ($recurringDetails["variant"] == "openinvoice"): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Bank account holder name') ?></label>
                    <span><?php echo $recurringDetails["bank_ownerName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('Bank Account Number') ?></label>
                    <span><?php echo $recurringDetails["bank_bankAccountNumber"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Country') ?></label>
                    <span><?php echo $recurringDetails["bank_countryCode"]; ?></span>
                </div>
            <?php elseif ($recurringDetails["variant"] == "sepadirectdebit" || $recurringDetails["variant"] == "ideal"): ?>
                <div class="columns three a">
                    <label><?php echo $this->__('Bank account holder name') ?></label>
                    <span><?php echo $recurringDetails["bank_ownerName"]; ?></span>
                </div>
                <div class="columns three b">
                    <label><?php echo $this->__('IBAN') ?></label>
                    <span><?php echo $recurringDetails["bank_iban"]; ?></span>
                </div>
                <div class="columns three c">
                    <label><?php echo $this->__('Country') ?></label>
                    <span><?php echo $recurringDetails["bank_countryCode"]; ?></span>
                </div>
            <?php endif;
            ?>
        <?php endif; ?>
    </li>
</ul>
