<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php //TODO add a form to add data here, currently only on Adyen. ?>
<?php $_code = $this->getMethodCode(); ?>

<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <?php echo $this->__('You will be redirected to Adyen website when you place an order.') ?>
    </li>
</ul>

<div>
    <span id="ipayment-elv-please-wait" style="display:none;" class="opc-please-wait">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle"
             alt=""/> &nbsp; <?php echo $this->__('Submitting payment information...') ?> &nbsp;
    </span>
</div>

