<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php if ($_info = $this->getInfo()): ?>
    <?php $boleto = unserialize($this->getInfo()->getPoNumber()) ?>
    <?php echo Mage::helper('adyen')->__(
        'Social Security Number: %s',
        $this->htmlEscape($boleto['social_security_number'])
    ) ?><br/>
    <?php echo Mage::helper('adyen')->__('Firstname: %s', $this->htmlEscape($boleto['firstname'])) ?><br/>
    <?php echo Mage::helper('adyen')->__('Lastname: %s', $this->htmlEscape($boleto['lastname'])) ?><br/>

    <?php if ($this->getInfo()->getOrder() != null) {
        echo Mage::helper('adyen')->__(
            'Boleto PDf: <a target="_blank" href="%s" title="Boleto PDF">Download</a>',
            $this->getInfo()->getOrder()->getAdyenBoletoPdf()
        ) ?><br/>
    <?php } ?>
<?php endif; ?>