<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php $disabled = $this->getMethod()->getHppOptionsDisabled(); ?>
<?php if ($disabled): ?>
    <?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br/>
<?php endif; ?>

<?php if ($_info = $this->getInfo()): ?>
    <?php $paymentMethod = $_info->getCcType() ?>
    <?php if (!empty($paymentMethod)): ?>
        <?php echo $this->__(
            'Payment Method: %s',
            $this->htmlEscape($_info->getAdditionalInformation('hpp_type_label'))
        ) ?>
        <br/>
    <?php endif; ?>
    <?php if (strpos($paymentMethod, "ideal") !== false): ?>
        <?php $bankData = $_info->getAdditionalInformation("hpp_issuer_id"); ?>
        <?php if (!empty($bankData)) : ?>
            <?php
            $label = $_info->getAdditionalInformation('hpp_type_bank_label');
            ?>
            <?php echo $this->__('Bank: %s', $this->htmlEscape($label)) ?><br/>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>