<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php if ($_info = $this->getInfo()): ?>
    <?php $sepa = unserialize($this->getInfo()->getPoNumber()) ?>
    <?php echo Mage::helper('adyen')->__('Bank account holder name: %s', $this->htmlEscape($sepa['account_name'])) ?>
    <br/>
    <?php echo Mage::helper('adyen')->__('IBAN: %s', $this->htmlEscape($sepa['iban'])) ?><br/>
    <?php echo Mage::helper('adyen')->__('Country: %s', $this->htmlEscape($sepa['country'])) ?><br/>
<?php endif; ?>