<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>

<?php if ($this->displayBoth()): ?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getExcludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeExcludeTax()) ?>
        </td>
    </tr>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getIncludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeIncludeTax()) ?>
        </td>
    </tr>
<?php elseif ($this->displayIncludeTax()) : ?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeIncludeTax()) ?>
        </td>
    </tr>
<?php else: ?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->escapeHtml($this->getTotal()->getTitle()) ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getPaymentFeeExcludeTax()) ?>
        </td>
    </tr>
<?php endif; ?>
