<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
$_code = $this->getMethodCode();
/** @var $this Adyen_Payment_Block_Form_Sepa */
?>


<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li id="AdyenApplePayError">
            <?php echo $this->__('Your browser does not support ApplePay or you don\'t have any active cards in your wallet.') ?>
            <input type="hidden" id="AdyenAllowApplePay" name="payment[allow_apple_pay]" value="0"/>
        </li>
    </ul>

    <script type="text/javascript">
        // check if apple pay is available for shopper
        if (window.ApplePaySession) {
            $('AdyenApplePayError').hide();
            $('AdyenAllowApplePay').setValue("1");
        }
    </script>
</fieldset>

