<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php $_code = $this->getMethodCode() ?>
<?php $disabled = $this->getHppOptionsDisabled(); ?>
<?php if ($disabled): ?>
    <fieldset class="form-list">
        <ul id="payment_form_<?php echo $_code ?>" style="display:none">
            <li>
                <?php echo $this->__('You will be redirected to Adyen website when you place an order.') ?>
            </li>
        </ul>
    </fieldset>
<?php endif; ?>
<?php if (count($this->getIssuers()) > 0): ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <label for="payment[adyen_issuer_type]">
                <?php echo $this->__('Choose Your Bank') ?>
            </label>
            <select class="adyen_select_issuer validate-select" name="payment[adyen_issuer_type]">
                <option value=""><?php echo $this->__('Choose Your Bank'); ?></option>
                <?php foreach ($this->getIssuers() as $_issuerId => $_issuerData): ?>
                    <option value="<?php echo $_issuerId ?>"
                            <?php if (isset($_issuerData['selected'])): ?>selected<?php
                            endif; ?>>
                        <?php echo $_issuerData['label']; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </li>
    </ul>
<?php endif; ?>
<?php
