<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php
/** @var Adyen_Payment_Block_Form_Ideal $this */
?>
<?php $_code = $this->getMethodCode() ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <label for="payment[adyen_ideal_type]">
            <?php echo $this->__('Choose Your Bank') ?>
        </label>
    </li>
    <?php

    $size = count($this->getIssuers());
    $count = 1;

    foreach ($this->getIssuers() as $_issuerId => $_issuerData): ?>
        <li>
            <label class="adyen-ideal-image-label" for="adyen_ideal_type_<?php echo $_issuerId ?>">
                <input type="radio" id="adyen_ideal_type_<?php echo $_issuerId ?>"
                       name="payment[adyen_issuer_type]" value="<?php echo $_issuerId ?>"
                       class="<?php if ($size == $count) {
                           echo 'validate-one-required-by-name';
                      } ?>"
                       <?php if (isset($_issuerData['selected'])): ?>checked<?php
                       endif; ?>

                />
                <img src="<?php echo $this->getIssuerImageUrl($_issuerData); ?>"
                     alt="<?php echo $_issuerData['label'] ?>"/>
            </label>
        </li>
        <?php
        $count++;
    endforeach; ?>
</ul>
