<div id="threeDS2">
    threeds2 in process...
    Please do not refresh or leave the page
    <script type="text/javascript"
            src="<?php echo Mage::helper('adyen')->getCheckoutCardComponentJs(); ?>"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript">
        var type = "<?php echo $this->getThreeds2Type();?>";
        var token = "<?php echo $this->getThreeds2Token();?>";
        var configuration = {
            locale: '<?php echo Mage::app()->getLocale()->getLocaleCode();?>'
        };

        var checkout = new AdyenCheckout(configuration);

        renderThreeDS2Component(type, token);

        /**
         * Rendering the 3DS2.0 components
         * To do the device fingerprint at the response of IdentifyShopper render the threeDS2DeviceFingerprint
         * component
         * To render the challenge for the customer at the response of ChallengeShopper render the
         * threeDS2Challenge component
         *
         * @param type
         * @param token
         */
        function renderThreeDS2Component(type, token) {
            var self = this;
            var threeDS2Node = document.getElementById('threeDS2');

            if (type == "IdentifyShopper") {
                self.threeDS2Component = checkout
                    .create('threeDS2DeviceFingerprint', {
                        fingerprintToken: token,
                        onComplete: function (result) {
                            processThreeDS2(result.data);
                        },
                        onError: function (error) {
                            console.log(JSON.stringify(error));
                        }
                    });
            } else if (type == "ChallengeShopper") {
                self.threeDS2Component = checkout
                    .create('threeDS2Challenge', {
                        challengeToken: token,
                        onComplete: function (result) {
                            processThreeDS2(result.data);
                        },
                        onError: function (error) {
                            console.log(JSON.stringify(error));
                        }
                    });
            }
            self.threeDS2Component.mount(threeDS2Node);
        }

        /**
         * The results that the 3DS2 components returns in the onComplete callback needs to be sent to the
         * backend to the /adyen/ThreeDS2Process endpoint and based on the response redirect to the success page
         * or redirect to cart and cancel the order
         * @param response
         */
        function processThreeDS2(data, error) {

            var url = '<?php echo $this->getUrl('adyen/ThreeDS2Process', array('_secure' => true)); ?>';
            var promise = new Promise(function (resolve, reject) {
                var ajaxReq = new $.ajax(url, {
                    parameters: {isAjax: 1, method: 'POST'},
                    success: function (result) {
                        resolve(result);
                    },
                    failure: function (result) {
                        reject(new Error("There was an error with 3ds2"));
                    },
                    data: {details: data, error: error}
                });
            });

            promise.then(function res(result) {
                if (result) {
                    var response = JSON.parse(result);
                    if (response.authentication) {
                        renderThreeDS2Component(response["resultCode"], response["authentication"]["threeds2.challengeToken"]);
                    } else if (response === "Authorised") {
                        window.location = "/checkout/onepage/success";
                    } else if (response === "Refused" || response === "Error") {
                        window.location = "/checkout/cart";
                    }
                } else {
                    window.location = "/checkout/cart";
                }
            });
        }

    </script>
</div>