<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2014 Adyen BV (http://www.adyen.com)
 */
?>
<?php
$ownerInformation = $this->getInfo()->getCcOwner();
echo $this->htmlEscape($this->getMethod()->getTitle());
?><br/>
<?php if ($_info = $this->getInfo()): ?>
    <?php if ($_info->getAdyenPspReference() == ''): ?>
        <?php echo Mage::helper('adyen')->__('Payment has not been processed yet.') ?> <br/>
    <?php else : ?>
        <?php
        $storeId = $this->getMethod()->getInfoInstance()->getOrder()->getStoreId();
        if ($this->getMethod()->getConfigDataDemoMode($storeId)): ?>
            <?php echo Mage::helper('adyen')->__(
                'Adyen PSP Reference: <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>',
                $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())
            ) ?>
            <br/>
        <?php else : ?>
            <?php echo Mage::helper('adyen')->__(
                'Adyen PSP Reference: <a href="https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>',
                $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())
            ) ?>
            <br/>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->getCcTypeName() != ""): ?>
        <?php echo Mage::helper('adyen')->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?><br/>
    <?php endif; ?>
    <?php if ($this->getInfo()->getCcLast4() != ""): ?>
        <?php echo Mage::helper('adyen')->__(
            'Credit Card Number: xxxx-%s',
            $this->htmlEscape($this->getInfo()->getCcLast4())
        ) ?><br/>
    <?php endif; ?>
<?php endif; ?>
<?php if ($this->htmlEscape($this->getInfo()->getAdyenAvsResult()) != ""): ?>
    <?php echo Mage::helper('adyen')->__('Avs result: %s', $this->htmlEscape($this->getInfo()->getAdyenAvsResult())) ?>
    <br/>
<?php endif; ?>

<?php if ($this->htmlEscape($this->getInfo()->getAdyenCvcResult()) != ""): ?>
    <?php echo Mage::helper('adyen')->__('Cvc result: %s', $this->htmlEscape($this->getInfo()->getAdyenCvcResult())) ?>
    <br/>
<?php endif; ?>
<?php if ($this->htmlEscape($this->getInfo()->getAdyenTotalFraudScore()) != ""): ?>
    <?php echo Mage::helper('adyen')->__(
        'Total fraud score: %s',
        $this->htmlEscape($this->getInfo()->getAdyenTotalFraudScore())
    ) ?><br/>
<?php endif; ?>
<?php if ($this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments')) != "" && $this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments')) > 1): ?>
    <?php echo Mage::helper('adyen')->__(
        'Number of installments: %s',
        $this->htmlEscape($this->getInfo()->getAdditionalInformation('number_of_installments'))
    ) ?><br/>
<?php endif; ?>
<?php if ($this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw()) != ""): ?>
    <?php echo Mage::helper('adyen')->__(
        'Raw acquirer response: %s',
        $this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw())
    ) ?><br/>
<?php endif; ?>
<?php if ($this->htmlEscape($this->getInfo()->getAdyenAuthCode()) != ""): ?>
    <?php echo Mage::helper('adyen')->__(
        'Authorisation code: %s',
        $this->htmlEscape($this->getInfo()->getAdyenAuthCode())
    ) ?><br/>
<?php endif; ?>
<?php if ($this->htmlEscape($this->getInfo()->getAdyenAcquirerReference()) != ""): ?>
    <?php echo Mage::helper('adyen')->__(
        'Acquirer reference: %s',
        $this->htmlEscape($this->getInfo()->getAdyenAcquirerReference())
    ) ?><br/>
<?php endif; ?>
