<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2019 Adyen B.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
/**
 * @category   Payment Gateway
 * @package    Adyen_Payment
 * @author     Adyen
 * @property   Adyen B.V
 * @copyright  Copyright (c) 2018 Adyen BV (http://www.adyen.com)
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br/>
<?php if ($_info = $this->getInfo()): ?>
    <?php if ($_info->getAdyenPspReference() == ''): ?>
        <?php echo Mage::helper('adyen')->__('Payment has not been processed yet.') ?> <br/>
    <?php else : ?>
        <?php if ($this->getMethod()->getConfigDataDemoMode()): ?>
            <?php echo Mage::helper('adyen')->__(
                'Adyen PSP Reference: <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>',
                $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())
            ) ?>
            <br/>
        <?php else : ?>
            <?php echo Mage::helper('adyen')->__(
                'Adyen PSP Reference: <a href="https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>',
                $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())
            ) ?>
            <br/>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw()) != ""): ?>
        <?php echo Mage::helper('adyen')->__(
            'Raw acquirer response: %s',
            $this->htmlEscape($this->getInfo()->getAdyenRefusalReasonRaw())
        ) ?><br/>
    <?php endif; ?>
    <?php if ($this->htmlEscape($this->getInfo()->getAdyenAuthCode()) != ""): ?>
        <?php echo Mage::helper('adyen')->__(
            'Authorisation code: %s',
            $this->htmlEscape($this->getInfo()->getAdyenAuthCode())
        ) ?><br/>
    <?php endif; ?>
    <?php if ($this->htmlEscape($this->getInfo()->getAdyenAcquirerReference()) != ""): ?>
        <?php echo Mage::helper('adyen')->__(
            'Acquirer reference: %s',
            $this->htmlEscape($this->getInfo()->getAdyenAcquirerReference())
        ) ?><br/>
    <?php endif; ?>
    <style>
        table.terminal-api-receipt {
            margin-top: 10px;
        }

        td.terminal-api-receipt-name {
            padding: inherit;
            font-weight: 700;
        }

        td.terminal-api-receipt-value {
            padding: inherit;
        }

        tr.terminal-api-receipt {
            padding-bottom: 5px;
        }
    </style>
    <?php echo $this->getMethod()->getInfoInstance()->getAdditionalInformation('receipt'); ?>
<?php endif; ?>
